# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build naftis

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: OSV check (table)
        continue-on-error: true
        run: ./osv-scanner --sbom bom.json --skip-git > ./osv.txt

      - name: OSV check (json)
        continue-on-error: true
        run: ./osv-scanner --sbom bom.json --format json --skip-git > ./osv.json

      - name: Commit and push SBOMs and OSVs
        run: |
          git config --global user.name 'Michael Gfeller'
          git config --global user.email '1214008+mgfeller@users.noreply.github.com'
          git add ./bom.json
          git add ./bom.xml
          git add ./osv.txt
          git add ./osv.json
          git commit -m "Updated SBOM and OSV"
          git push

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            user/app:latest
            user/app:0.0.1
          build-args: JAR_FILE=target/naftis-0.0.1-SNAPSHOT.jar

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6